let allMusic = [
    {
        name: "アカツキワイナリー",
        artist: "HOYO-MiX",
        img: "モンド.artwork.jpg",
        src :"アカツキワイナリー.mp3",
    },
    {
        name: "七彩の庭園",
        artist: "HOYO-MiX",
        img: "遺失と忘却の島.artwork.jpg",
        src :"七彩の庭園.mp3",
    },
    {
        name: "温かき思い出",
        artist: "HOYO-MiX",
        img: "遺失と忘却の島.artwork.jpg",
        src :"温かき思い出.mp3",
    },
    {
        name: "波を裂く寒光",
        artist: "HOYO-MiX",
        img: "遺失と忘却の島.artwork.jpg",
        src :"波を裂く寒光.mp3",
    },
    {
        name: "波乱万丈",
        artist: "HOYO-MiX",
        img: "遺失と忘却の島.artwork.jpg",
        src :"波乱万丈.mp3",
    },
    {
        name: "背水の陣",
        artist: "HOYO-MiX",
        img: "遺失と忘却の島.artwork.jpg",
        src :"背水の陣.mp3",
    },
    {
        name: "山岳は崩れ",
        artist: "HOYO-MiX",
        img: "真珠の歌.artwork.jpg",
        src :"山岳は崩れ.mp3",
    },
    {
        name: "スメール",
        artist: "HOYO-MiX",
        img: "スメール.artwork.jpg",
        src :"スメール.mp3",
    },
    {
        name: "璃月",
        artist: "HOYO-MiX",
        img: "璃月.artwork.jpg",
        src :"璃月.mp3",
    },
    {
        name: "三千娑界の御詠歌",
        artist: "HOYO-MiX",
        img: "流変の砂、さやさやと.artwork.jpg",
        src :"三千娑界の御詠歌.mp3",
    },
    {
        name: "三千娑界の御詠歌 (ライブ編集版)",
        artist: "HOYO-MiX",
        img: "真珠の歌3.artwork.jpg",
        src :"三千娑界の御詠歌 (ライブ編集版).mp3",
    },
    {
        name: "いつかの知恵、いつかの願い",
        artist: "HOYO-MiX",
        img: "スメール.artwork.jpg",
        src :"いつかの知恵、いつかの願い.mp3",
    },
    {
        name: "にぎやかな港",
        artist: "HOYO-MiX",
        img: "スメール.artwork.jpg",
        src :"にぎやかな港.mp3",
    },
    {
        name: "渦巻く激流",
        artist: "HOYO-MiX",
        img: "スメール.artwork.jpg",
        src :"渦巻く激流.mp3",
    },
    {
        name: "繁忙なモンドの午後",
        artist: "HOYO-MiX",
        img: "モンド.artwork.jpg",
        src :"繁忙なモンドの午後.mp3",
    },
    {
        name: "彷徨する輝き",
        artist: "HOYO-MiX",
        img: "モンド.artwork.jpg",
        src :"彷徨する輝き.mp3",
    },
    {
        name: "ルーのメロディー",
        artist: "HOYO-MiX",
        img: "遺失と忘却の島.artwork.jpg",
        src :"ルーのメロディー.mp3",
    },
    {
        name: "雷霆のご威光",
        artist: "HOYO-MiX",
        img: "遺失と忘却の島.artwork.jpg",
        src :"雷霆のご威光.mp3",
    },
    {
        name: "麟躍幽岩",
        artist: "HOYO-MiX",
        img: "真珠の歌.artwork.jpg",
        src :"麟躍幽岩.mp3",
    },
    {
        name: "燼滅の舞",
        artist: "HOYO-MiX",
        img: "遺失と忘却の島.artwork.jpg",
        src :"燼滅の舞.mp3",
    },
    {
        name: "BEACON",
        artist: "平沢進",
        img: "beacon.jpg",
        src :"BEACON.mp3",
    },
    {
        name: "遮眼大師",
        artist: "核P-MODEL",
        img: "遮眼大師.jpg",
        src :"遮眼大師.mp3",
    },
]